# Form implementation generated from reading ui file 'E:\pyProj\python-collection\sccnnDownload.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(436, 441)
        self.labelKeyword = QtWidgets.QLabel(Dialog)
        self.labelKeyword.setGeometry(QtCore.QRect(30, 40, 101, 16))
        self.labelKeyword.setObjectName("labelKeyword")
        self.labelSavePath = QtWidgets.QLabel(Dialog)
        self.labelSavePath.setGeometry(QtCore.QRect(30, 80, 91, 16))
        self.labelSavePath.setObjectName("labelSavePath")
        self.lineEditKeyWord = QtWidgets.QLineEdit(Dialog)
        self.lineEditKeyWord.setGeometry(QtCore.QRect(150, 40, 121, 20))
        self.lineEditKeyWord.setObjectName("lineEditKeyWord")
        self.lineEditSavePath = QtWidgets.QLineEdit(Dialog)
        self.lineEditSavePath.setGeometry(QtCore.QRect(150, 80, 121, 20))
        self.lineEditSavePath.setObjectName("lineEditSavePath")
        self.pushBtnBrowser = QtWidgets.QPushButton(Dialog)
        self.pushBtnBrowser.setGeometry(QtCore.QRect(290, 80, 81, 31))
        self.pushBtnBrowser.setObjectName("pushBtnBrowser")
        self.pushBtnDown = QtWidgets.QPushButton(Dialog)
        self.pushBtnDown.setGeometry(QtCore.QRect(40, 130, 101, 31))
        self.pushBtnDown.setObjectName("pushBtnDown")
        self.pushBtnCancle = QtWidgets.QPushButton(Dialog)
        self.pushBtnCancle.setGeometry(QtCore.QRect(220, 130, 121, 31))
        self.pushBtnCancle.setObjectName("pushBtnCancle")
        self.textInfo = QtWidgets.QTextBrowser(Dialog)
        self.textInfo.setGeometry(QtCore.QRect(30, 200, 391, 231))
        self.textInfo.setObjectName("textInfo")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEditKeyWord, self.lineEditSavePath)
        Dialog.setTabOrder(self.lineEditSavePath, self.pushBtnBrowser)
        Dialog.setTabOrder(self.pushBtnBrowser, self.pushBtnDown)
        Dialog.setTabOrder(self.pushBtnDown, self.pushBtnCancle)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "素材下载器"))
        self.labelKeyword.setText(_translate("Dialog", "搜索关键字:"))
        self.labelSavePath.setText(_translate("Dialog", "保存路径:"))
        self.pushBtnBrowser.setText(_translate("Dialog", "浏览..."))
        self.pushBtnDown.setText(_translate("Dialog", "开始下载"))
        self.pushBtnCancle.setText(_translate("Dialog", "取消下载"))
