# Form implementation generated from reading ui file '.\CZX\move_files.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_moveFilesDlg(object):
    def setupUi(self, moveFilesDlg):
        moveFilesDlg.setObjectName("moveFilesDlg")
        moveFilesDlg.resize(524, 290)
        self.horizontalLayout = QtWidgets.QHBoxLayout(moveFilesDlg)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=moveFilesDlg)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.HLayoutBrowser = QtWidgets.QHBoxLayout()
        self.HLayoutBrowser.setObjectName("HLayoutBrowser")
        self.lineEditFolder = QtWidgets.QLineEdit(parent=moveFilesDlg)
        self.lineEditFolder.setObjectName("lineEditFolder")
        self.HLayoutBrowser.addWidget(self.lineEditFolder)
        self.pushBtnBrowser = QtWidgets.QPushButton(parent=moveFilesDlg)
        self.pushBtnBrowser.setObjectName("pushBtnBrowser")
        self.HLayoutBrowser.addWidget(self.pushBtnBrowser)
        self.pushBtnOk = QtWidgets.QPushButton(parent=moveFilesDlg)
        self.pushBtnOk.setObjectName("pushBtnOk")
        self.HLayoutBrowser.addWidget(self.pushBtnOk)
        self.HLayoutBrowser.setStretch(0, 8)
        self.HLayoutBrowser.setStretch(1, 1)
        self.HLayoutBrowser.setStretch(2, 1)
        self.verticalLayout.addLayout(self.HLayoutBrowser)
        self.textBrowser = QtWidgets.QTextBrowser(parent=moveFilesDlg)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(moveFilesDlg)
        QtCore.QMetaObject.connectSlotsByName(moveFilesDlg)

    def retranslateUi(self, moveFilesDlg):
        _translate = QtCore.QCoreApplication.translate
        moveFilesDlg.setWindowTitle(_translate("moveFilesDlg", "振兴集团-文件整理小工具"))
        self.label.setText(_translate("moveFilesDlg", "重命名目录:"))
        self.pushBtnBrowser.setText(_translate("moveFilesDlg", "浏览..."))
        self.pushBtnOk.setText(_translate("moveFilesDlg", "执行"))
        self.textBrowser.setHtml(_translate("moveFilesDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">查找文件夹前面的身份证号，并创建同名文件夹</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">并将有此身份证号的文件移至此文件夹中</span></p>\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:16pt;\"><br /></p>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:48pt; color:#aa0000;\">振兴集团</span></p></body></html>"))
